# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # run make all
    - make all
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  goos:
  - darwin
  - linux
  - windows
  ldflags:
  - -s -w -X github.com/mrz1836/{{ .ProjectName }}/cmd.Version={{ .Version }}
archives:
- wrap_in_directory: app
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
release:
  prerelease: true
  name_template: "Release v{{.Version}}"
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^.github:'
    - '^test:'
